redxzeta/Awesome-Adoption

- src/App.js
- src/components/layout/NavigationBar.js
- src/components/pets/Pets.js
Pet category images misalignment is fixed. Buttons are level now.
> Pet categories alignment fix

- package-lock.json
- package.json
- src/components/pets/PetType.js
Zip code validation integrated to search form. The entry of invalid zip code will prevent component re-rendering and will display the error message in the text field.
> zip code validation added

- src/components/pets/PetInfo.js
Fixes[#10 ]
I have added buttons to allow navigation between photos of pet.
> added feature to navigate between all pet photos

- src/App.js
- src/components/home/Home.js
- src/components/home/home.css
> Add featured pets

- src/components/home/Home.js
- src/components/home/home.css
- src/components/pets/PetType.js
- src/components/pets/pets.css
> Fixed zip code wrapping, static width and height of pet images

- src/components/pets/PetInfo.js
- src/components/pets/PetType.js
name of pet gets too long #55 
added truncation to pet names on the PetType.js
added regex to  to pet names on the PetType.js
added regex to  to pet names on the PetInfo.js
> #55 added trucation via css to long pet names, added regex to pet.name

- src/components/layout/NavigationBar.js
- yarn.lock
Upgraded react-bootstrap version to @1.6.0
Resolves: #36
> Style - Align menu to right

- .gitignore
- package.json
- src/App.test.js
- src/components/donate/Donate.jsx
- src/components/donate/DonateCard.js
- src/components/donate/__tests__/donate.test.js
- yarn.lock
> adding tests for Donate

- src/components/resources/Resources.js
- src/components/resources/resources.css
About #70, here's what I did:
Replaced `<b>` tags with `<span>` tags so I could make it **bold** using CSS.
Fixed a few typos.
Edited `resources.css`'s old code a bit.
> Edited Resources.js & resources.css

- package-lock.json
- src/App.js
- src/components/auth/auth.css
- src/components/auth/login.jsx
- src/components/auth/register.jsx
- src/components/layout/NavigationBar.js
This is my first PR. Let me know if you have any feedback!
> Login and Register page created #75

- package-lock.json
- src/components/pets/Pets.js
- src/components/pets/pets.css
Text added on hover successfully.
> Text added on hover.

- src/components/donate/charities.json
Hacktoberfest PR for https://github.com/redxzeta/Awesome-Adoption/issues/82!
@redxzeta please review!
> Add SPCA of Wake County to charities.json

- src/components/layout/NavigationBar.js
Add divider to the dropdown to seperate all pets
> seperate all-pets in the dropdown

- src/components/donate/charities.json
> Add Bald Is Beautiful to donation page

- src/components/accounts/profile/Profile.jsx
- src/components/accounts/profile/profile.css
- yarn.lock
Enhanced UI of profile. Made a responsive card to display a thumbnail and story.
> Enhanced the design of profile

- src/components/home/Home.js
- src/components/layout/NavigationBar.js
> put heading into the navbar

- src/components/home/Home.js
Another small UI improvement, regarding issue #205
> add shadow to dog image in the home page

- src/context/TokenContext.js
> File for TokenContext.Provider Created

- src/components/about/__tests__/about.test.js
- src/useHooks/useFetch.js
- src/utils/LoaderComponent.js
- testing changes
- fixed tests based on feedback from Julian
- testing changes
- fixed tests based on feedback from Julian
> adding about tests 

- package.json
- src/components/donate/Donate.jsx
- src/components/donate/DonateModal.jsx
Please do check out the changes related to the issue [#174](https://github.com/redxzeta/Awesome-Adoption/issues/174) and update me if any further changes.
The Submit button lets you check various validations.
> Created 'Submit Organization' Model

- src/components/pets/PetInfo.js
- src/components/pets/__tests__/__snapshots__/petInfo.test.js.snap
- src/components/pets/__tests__/petInfo.test.js
Fixes #208 
I made a branch off of the `paw-dev` branch. The data in `petInfo.js` is the one on the `paw-dev` branch and not the `main` branch.
Some of the code in `petInfo.js` originally kept breaking the app, especially when refreshing the page. The problem was some objects returned null. So I added conditions for them. The issue I think is `usePetAuth()` for `tokenHeaders` is async,  and it also affects `useFetch()`, so sometimes not all the data have been loaded when the html elements are rendering. 
Also, `navigate.share` doesn't exist on all browsers. I first tried it on FireFox and it crashed the app, so I added a condition to it as well. 
I used mocked data for simulating data from `useFetch()`. Since its an imported function, I don't think it should be tested in `petInfo`, and …
> Adding tests for petInfo

- src/components/donate/Donate.jsx
- src/components/donate/__tests__/donate.test.js
fixes #231 add tests for donate page
Wrote a test to: 
- Test for filtering
- Drop down
- Expecting the elements from the list
> Added tests for donate page filter

- src/components/home/Home.js
- src/components/home/home.css
-> Made fetchPetsData global function
-> Added refresh button.
> added refresh button

- src/App.js
- src/components/about/About.js
- src/components/about/Contributors.jsx
- src/components/about/__tests__/about.test.js
- src/setupTests.js
- src/swrconfigtest.js
changing some tests based on swr
> using swr on about page

- src/components/home/Home.js
- src/components/pets/PetType.js
- src/components/shared/PlaceHolderCard/PlaceHolderCard.css
- src/components/shared/PlaceHolderCard/index.js
#241 
I have created an components for the place holder card.
I have changed out the spinner on the `Home.js` and `PetType.js`.
This is what the Home page will look like when it loads the card.
And this is what the Pets page will look when loading.
Let me know if there any adjustments that you want to change.
> Replace spinner with Placeholder cards for home and pet page.

- src/components/home/Home.js
- src/components/home/__tests__/home.test.js
- src/routes/API.js
- src/testServer.js
- src/utils/homePageFetcher.js
Hi, this is my solution for el issue #261 
- Now useSWR hook is used to fetch the petList from the API
- While the app is fetching the petList, the "Loading .." label and the placeholders of the cards are shown
- When there is an error fetching the list of pets, now there is a message that warns the user of the error
- Mutate with SWR implemented to refresh the data
- Some HomePage tests added
Let me know if there is any change I can make :)
>  Refactoring Home Page Structure #261 

- src/App.css
- src/App.js
- src/components/home/Home.js
- src/components/home/home.css
> Added a hero section on the home page instead of an image of a pug 

- src/components/accounts/__tests__/Register.test.js
- src/components/accounts/__tests__/SLogin.test.js
- src/components/donate/__tests__/donate.test.js
- src/components/pets/__tests__/pet.type.test.js
updating tests on updated userEvent
> feat: update tests to use userEvent@14

- src/components/home/Home.tsx
- src/components/pets/PetType.tsx
- src/utils/petInfoFetcher.ts
fix home page mutate by setting it to null.
it shows the spinner
> fix: home page mutate

- src/App.tsx
- src/components/accounts/ForgotPassword.tsx
- src/components/layout/NavigationBar.tsx
Removing User Stories to be fixed later
> 306 Fix ForgotPassword

- src/App.tsx
- src/components/accounts/settings/Settings.tsx
- src/components/accounts/settings/settings.css
- src/components/layout/NavigationBar.tsx
> feat: Created Settings page

- src/components/layout/FavoriteButton/index.tsx
- src/components/pets/Favorites/FavoriteSection.tsx
- fetching favorite pets from supabase by passing pet id as filter
- showing number of people who favorited pet
- no count shown if no one has favorited pet, else shows number of people
> feat: Show the number of people who favorited pet

- .github/workflows/auto-merge.yml
- .github/workflows/greetings.yml
- .github/workflows/node.js.yml
- .github/workflows/prLint.yml
- .github/workflows/tag.yml
Patching github actions for dependabot
> patch: github actions

- package.json
- src/components/layout/FavoriteButton/index.tsx
- src/components/layout/NavigationBar.tsx
- src/components/pets/PetInfo.tsx
- src/components/pets/PetType.tsx
- yarn.lock
Migrated all heroIcons from v2 to v3
(issue #428)
> migrated from heroicons v2 to v3

- src/components/layout/NavigationBar.tsx
Added the missing mobile dropdown nav links to match desktop version.
Included a fix to not have the Home link always highlighted in mobile dropdown
Closes #438
> feat: Missing menu in mobile view

- .github/workflows/greetings.yml
Commented few lines for testing the greeting work flow https://github.com/redxzeta/Awesome-Adoption/issues/440
> fix: updated the workflow

- src/components/layout/NavigationBar.tsx
- src/components/themeToggle/themeToggle.tsx
- tailwind.config.js
#397 issue solved. 
If you don't like the dark theme colors then do let me know so that I can made further changes.
**Have a look below.**
> feat: implemeted dark mode

- src/components/accounts/profile/Profile.tsx
- src/components/pets/Favorites.tsx
- src/utils/petInfoFetcher.ts
pets get removed from api so here's a short term solution
> fix: favorited removed pets

- src/components/pets/PetInfo.tsx
Fixes #467 
|Available (safari) | Unavailable (chrome) |
|-|-|
|<img width="1790" alt="Screenshot 2022-10-10 at 10 09 00 PM" src="https://user-images.githubusercontent.com/25058106/194914891-1bb9b0c3-127a-4071-8552-a3700b134e30.png">|<img width="1792" alt="Screenshot 2022-10-10 at 10 09 20 PM" src="https://user-images.githubusercontent.com/25058106/194914922-cd6d3130-c324-4055-89eb-f8fcc0e6a56e.png">|
> fix: display share based on feature availability

- src/components/pets/Favorites.tsx
**Changes proposed:**
- Dropdown section for filter on click.
Added a right-side dropdown menu to maintain hierarchy among the dropdown menus across the website.
> feat: filter on favorite pets added

- src/App.tsx
- src/components/accounts/settings/resetPassword.tsx
moves the reset password to tailwind and changes it from bootstrap to the same form control as the login
closes #479
> changed the reset password to use Tailwind and removed bootstrap

- src/components/pets/Favorites.tsx
Added buddies type and show message when there is no buddy. Fix #503.
1. All types
2. Dog type
3. Horse type: no Horse added to favourite
> feat: add pet type to favourite pets filter (#503)

- src/components/resources/Resources.tsx
Description of PR that completes issue here...
updated content of resources
- Description of changes
(prefer animated gif)
Closes [TICKET-14](https://linktoticket.com/ticket-number-14)
> fix: update resources

- src/components/home/Home.tsx
clicking on get started button scrolls down to featured pet in home page
> fix: Update Home.tsx
